-- MySQL Script generated by MySQL Workbench
-- 03/04/15 10:40:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TrainApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TrainApp` ;

-- -----------------------------------------------------
-- Schema TrainApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainApp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `TrainApp` ;

-- -----------------------------------------------------
-- Table `TrainApp`.`Pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`Pays` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`Pays` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainApp`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`User` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Professionel` TINYINT(1) NOT NULL,
  `Mail` VARCHAR(45) NOT NULL,
  `Abonné` TINYINT(1) NOT NULL,
  `PaysID` INT NOT NULL,
  PRIMARY KEY (`ID`, `PaysID`),
  INDEX `fk_User_Pays_idx` (`PaysID` ASC),
  CONSTRAINT `fk_User_Pays`
    FOREIGN KEY (`PaysID`)
    REFERENCES `TrainApp`.`Pays` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainApp`.`Newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`Newsletter` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`Newsletter` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Contenu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainApp`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`Produit` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`Produit` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Descriptif` VARCHAR(45) NOT NULL,
  `Prix` VARCHAR(45) NOT NULL,
  `Stock` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainApp`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`Commande` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`Commande` (
  `ID` INT NOT NULL,
  `Produit_ID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `Quantite` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`ID`, `Produit_ID`, `UserID`),
  INDEX `fk_Commande_Produit1_idx` (`Produit_ID` ASC),
  INDEX `fk_Commande_User1_idx` (`UserID` ASC),
  CONSTRAINT `fk_Commande_Produit1`
    FOREIGN KEY (`Produit_ID`)
    REFERENCES `TrainApp`.`Produit` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `TrainApp`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainApp`.`Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrainApp`.`Feedback` ;

CREATE TABLE IF NOT EXISTS `TrainApp`.`Feedback` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Note` INT NOT NULL,
  `Message` VARCHAR(45) NOT NULL,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `User_ID`),
  INDEX `fk_Feedback_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `TrainApp`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
